# fly.toml app configuration file generated for searching-science on 2024-11-24T21:40:30-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'searching-science'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
